apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: crm-kafka-activity-CHANGE-ME # ! Must be the same as the Kafka Topic name
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  env:
    - name: KAFKA_CLIENTID
      value: crm-kafka-activity-CHANGE-ME # ! Same as above
    - name: KAFKA_TOPIC
      value: team-dialog.crm-kafka-activity-CHANGE-ME # ! Namespace + same as above
    - name: EMP_ENV
      value: dev # ! prod or dev
    - name: EMP_TOPIC
      value: kafka-CHANGE-ME # ! Must be the same as the Salesforce Push Topic name (PUSH_TOPIC_NAME)
  kafka:
    pool: nav-dev # ! nav-dev or nav-prod
  webproxy: true
  image: "{{ image }}"
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: salesforce.com
        - host: navdialog.my.salesforce.com
        - host: test.salesforce.com
        - host: navdialog--preprod.my.salesforce.com
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: false
  filesFrom:
    - secret: emp-login
      mountPath: /var/run/secrets/my-secret
  envFrom:
    - secret: emp-login
