apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: crm-kafka-activity-oppgaver-v2 # ! Kafka Topic name used in other apps
  namespace: team-dialog
  labels:
    team: team-dialog
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: team-dialog
      application: crm-kafka-activity-oppgaver # ! Same as above
      access: readwrite
    - team: team-dialog
      application: kafka-reader
      access: read
    - team: dvh-arbeid
      application: dvh-arbeidsgiverkontakt-konsument
      access: read