apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: crm-kafka-activity-NAME # ! Kafka Topic name used in other apps
  namespace: team-dialog
  labels:
    team: team-dialog
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "false"
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: team-dialog
      application: crm-kafka-activity-NAME # ! Same as above
      access: readwrite