name: Build, push, and deploy

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "build.gradle"
      - "Dockerfile"
  push:
    paths:
      - ".nais/**"
      - "!.nais/README.md"
      - "src/**"
      - "build.gradle"
      - "Dockerfile"

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/crm-kafka-activity:${{ github.sha }}
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
jobs:
  # ----------------------------- #
  # --------- run tests --------- #
  # ----------------------------- #

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Build and run tests
        run: ./gradlew clean build --info

  # ----------------------------- #
  # ----------- build ----------- #
  # ----------------------------- #

  build:
    name: Build & push Docker Image
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Build JAR
        run: ./gradlew clean build shadowJar -x test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --pull --tag ${IMAGE}
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  # ----------------------------- #
  # ------- setup matrix -------- #
  # ----------------------------- #

  setup-matrix:
    name: Setup Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      emptyMatrix: ${{ steps.set-matrix.outputs.emptyMatrix }}
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # set matrix
      - name: Set Matrix
        id: set-matrix
        run: |
          echo Checking which configurations inside .nais/ were changed...

          MATRIX=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep .nais/ | cut -d '/' -f 2 | sort -u | paste -d',' -s )

          if [[  -z "${MATRIX// }" ]]; then
            echo "No changed configuration in .nais/"
            echo "::set-output name=emptyMatrix::true"
            echo "::set-output name=matrix::[]"
          else
            JSON=$(jq -c -n --arg v $MATRIX '{"resource": $v|split(",")}')
            echo "Apps to re-deploy: $MATRIX"
            echo "::set-output name=matrix::$JSON"
            echo "::set-output name=emptyMatrix::false"
          fi

          echo Checking if Dockerfile, /src or build.gradle was changed as well. Then, all apps will be re-deployed...
          data=$(git diff --name-only HEAD^ HEAD)
          for i in $data; do

              row=$(echo ${i%%/} | cut -d '/' -f 1)
              
              # if changed file is Dockerfile, inside /src or build.gradle
              if [  "$row" = "Dockerfile" ] || [  "$row" = "src" ] || [  "$row" = "build.gradle" ]; then
                  echo $row was changed, so all apps are re-deployed
                  
                  # cause all apps to re-deploy
                  MATRIX=$(for i in $(ls -d .nais/*/); do echo ${i%%/}; done | grep .nais/ | cut -d '/' -f 2 | paste -d',' -s )
                  echo "Apps to re-deploy: $MATRIX"

                  JSON=$(jq -c -n --arg v $MATRIX '{"resource": $v|split(",")}')
                  echo "::set-output name=matrix::$JSON"
                  echo "::set-output name=emptyMatrix::false"
              fi
          done

  # ----------------------------- #
  # -------- deploy dev --------- #
  # ----------------------------- #

  deploy-dev:
    name: Deploy to dev-gcp
    needs: [build, setup-matrix]
    runs-on: ubuntu-latest
    if: needs.setup-matrix.outputs.emptyMatrix == 'false'
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/${{ matrix.resource }}/dev.yml

  # ----------------------------- #
  # -------- deploy prod -------- #
  # ----------------------------- #

  deploy-prod:
    name: Deploy to prod-gcp
    needs: [build, setup-matrix]
    runs-on: ubuntu-latest
    if: needs.setup-matrix.outputs.emptyMatrix == 'false' && github.ref == 'refs/heads/main'
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/${{ matrix.resource }}/prod.yml
