name: Deploy Kafka Topics to Aiven

on:
  push:
    branches: main
    paths: .topics/kafka-topics/**

jobs:
  # ----------------------------- #
  # ------- setup matrix -------- #
  # ----------------------------- #

  setup-matrix:
    name: Setup Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      emptyMatrix: ${{ steps.set-matrix.outputs.emptyMatrix }}
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # set matrix
      - id: set-matrix
        run: |
          MATRIX=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep .topics/kafka-topics/ | cut -d '/' -f 3 | sort -u | paste -d',' -s )
          echo Matrix is $MATRIX
          if [[  -z "${MATRIX// }" ]]; then
            echo "Empty matrix"
            echo "::set-output name=emptyMatrix::true"
            echo "::set-output name=matrix::[]"
          else
            JSON=$(jq -c -n --arg v $MATRIX '{"topic": $v|split(",")}')
            echo "matrix: $JSON"
            echo "::set-output name=matrix::$JSON"
            echo "::set-output name=emptyMatrix::false"
          fi

  # ----------------------------- #
  # ------- deploy preprod ------ #
  # ----------------------------- #

  deploy-dev:
    name: Deploy Dev
    needs: setup-matrix
    runs-on: ubuntu-latest
    if: needs.setup-matrix.outputs.emptyMatrix == 'false'
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # deploy to dev gcp
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .topics/kafka-topics/${{ matrix.topic }}/topic.yml
          VARS: .topics/kafka-topics/${{ matrix.topic }}/dev-vars.yml
          PRINT_PAYLOAD: true

  # ----------------------------- #
  # ----- deploy production ----- #
  # ----------------------------- #

  deploy-prod:
    name: Deploy Production
    needs: setup-matrix
    runs-on: ubuntu-latest
    if: needs.setup-matrix.outputs.emptyMatrix == 'false'
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # deploy to prod gcp
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .topics/kafka-topics/${{ matrix.topic }}/topic.yml
          VARS: .topics/kafka-topics/${{ matrix.topic }}/prod-vars.yml
          PRINT_PAYLOAD: true
